author: Wojciech Danilo
bug-reports: https://github.com/wdanilo/dependent-state/issues
category: Data
copyright: Copyright (C) 2015 Wojciech Danilo
default-extensions: [ConstraintKinds, DataKinds, DefaultSignatures, DeriveDataTypeable,
  DeriveFoldable, DeriveFunctor, DeriveGeneric, DeriveTraversable, DoAndIfThenElse,
  EmptyDataDecls, FlexibleContexts, FlexibleInstances, GeneralizedNewtypeDeriving,
  InstanceSigs, LambdaCase, MultiParamTypeClasses, NoImplicitPrelude, OverloadedStrings,
  StandaloneDeriving, TemplateHaskell, TupleSections, TypeOperators, ViewPatterns,
  TypeFamilies]
dependencies: [base >=4.6 && <4.10, lens, mtl, prologue, primitive, exceptions, lens-utils,
  constraints, data-default, typelevel, transformers, transformers-base]
ghc-options: [-Wall, -O2]
homepage: https://github.com/wdanilo/dependent-state
library: {source-dirs: src}
license: Apache-2.0
maintainer: Wojciech Danilo <wojciech.danilo@gmail.com>
name: dependent-state
stability: experimental
synopsis: Control structure similar to Control.Monad.State, allowing multiple nested
  states, distinguishable by provided phantom types.
version: 1.0.15
